### ISSUE TITLE
GMV Animation Script Not Working for Northern California M7.0 Earthquake

### ISSUE THREAD

**Issue by datuadiatma** [iris-edu/gmv#2] opened 2024-12-13 17:55 UTC
I'm trying to create a GMV (Ground Motion Visualization) animation of the December 5, 2024 Northern California M7.0 earthquake for teaching purposes at Florida State University. However, I'm encountering issues getting the script to produce the animation. Would appreciate help troubleshooting.

### Environment

OS: Debian
Python Environment: Miniconda3 (pyquake environment)

### Scripts Used
```bash
#!/usr/bin/sh
/home/datu/miniconda3/envs/pyquake/bin/python src/gmv_generalized.py \
  --band=LH,BH \
  --comp=1 \
  --net=all \
  --etime="2024-12-05T18:44:21" \
  --title="December 5, 2024, Northern California Coast M7.0" \
  --emag=7.0 \
  --depth=10.0 \
  --eloc="40.374,-125.022" \
  --region=na \
  --dur=1200 \
  --sizem=6.0 \
  --delay=-180 \
  --qscale=3.5 \
  --gain=3 \
  --std=0.05 \
  --gc \
  --rsta=FSUO \
  --output=GMV_NorCal_2024_M7
```
### Issue
The script runs but doesn't produce the expected animation. It stops during data fetching process (after running for ~30 minutes). The error says something along the line the trace is out of index or something like that.

So my questions are:
1. Are there any common issues I should check first?
2. Are all the parameters in my script correctly formatted?
3. Does the script require any additional dependencies or data files?

While the immediate need has passed (class is over), I'd like to resolve this for future teaching demonstrations.

Thanks in advance,
Datu

**Comment by manoch-iris** [comment] 2024-12-16 09:40
Hi Datu,

Thank you for reaching out. Before we proceed, could you please let us know if you have made any changes to the parameter file? If so, what changes were made?

Thanks,
--manoch

**Comment by datuadiatma** [comment] 2024-12-16 13:58
Hi Manoch

I have not made any changes to the gmv_param.py. I ran the code by creating a bash script as shown in my previous post.

Thanks,
Datu

**Comment by manoch-iris** [comment] 2024-12-16 14:08
Hi Datu,

Thank for for confirming. We will look into this and get back to you.

Cheers,
--manocj

**Comment by manoch-iris** [comment] 2024-12-16 20:21
Dear Datu,

Thank you for bringing this to our attention. Based on the information you provided, we were able to replicate the issue. The problem was caused by an empty trace sent by a station that unfortunately passed through the QC section. A fix has been applied, and R1.1 should now run without any issues.

Please let me know if you have any questions.

Best regards,
--manoch

**Closed as completed by manoch-iris** 2024-12-16 20:21 UTC

**Comment by datuadiatma** [comment] 2024-12-17 18:09
Hi Manoch,

Thank you for the response. I successfully ran the updated version (R.1.1), but I've noticed a discrepancy in the reference station selection:

I explicitly set the reference station using `--rsta=FSUO` (FSU Observatory). However, the output log shows:
```bash
............2024-12-17 10:47:12 START............
[INFO] Reference station MFID from network IW
[INFO] Running for region na.
[INFO] Magnitude list ['7.0'].
```

This discrepancy is also reflected in the generated video, which displays MFID's seismic trace instead of FSUO's.

Could you help me understand why the program might be defaulting to MFID despite the FSUO specification? Thank you for your assistance.

Datu

**Comment by manoch-iris** [comment] 2024-12-17 19:35
Hi Datu,

I am glad to hear that it worked for you. Ref sta fix is easy, just add the
reference station network also
  --rnet=GS \
I will update the documentation to make this more clear.

Best,
--manoch
